/** Standard queue token statuses */
const TOKEN_STATUS = {
  WAITING: "WAITING",
  RESERVED: "RESERVED",
  SERVING: "SERVING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const ACTIVE_STATUSES = [
  TOKEN_STATUS.WAITING,
  TOKEN_STATUS.RESERVED,
  TOKEN_STATUS.SERVING,
];

const TERMINAL_STATUSES = [TOKEN_STATUS.COMPLETED, TOKEN_STATUS.CANCELLED];

module.exports = {
  TOKEN_STATUS,
  ACTIVE_STATUSES,
  TERMINAL_STATUSES,
};
